name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      INSTANCE_NAME: "apetech-vm"
      ZONE: "us-central1-a"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      - name: Build application
        run: |
          npm install
          npm run build

      - name: Comprimir la carpeta de construcción para la transferencia
        run: |
          tar -czf build.tar.gz build

      - name: Transferir el archivo comprimido a la VM
        run: |
          gcloud compute scp build.tar.gz rmanzimerica@$INSTANCE_NAME:/home/rmanzimerica --zone=$ZONE

      - name: Descomprimir y mover el build en la VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            cd /home/rmanzimerica
            rm -rf asociacion_apetech/build
            mkdir -p asociacion_apetech
            tar -xzf build.tar.gz -C /home/rmanzimerica/asociacion_apetech
          " -- -o StrictHostKeyChecking=no

      - name: Reiniciar PM2
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            pm2 restart my-app
          " -- -o StrictHostKeyChecking=no








