name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Esto ejecutará el despliegue solo en el branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  # Define las variables globalmente para el job
      INSTANCE_NAME: "apetech-vm"
      ZONE: "us-central1-a"  # Ajusta a la zona de tu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      - name: Comprimir la carpeta de construcción para la transferencia
        run: |
          tar -czf build.tar.gz build
          ls -lh build.tar.gz  # Verificar el tamaño del archivo

      - name: Esperar propagación de clave SSH
        run: sleep 120  # Aumenta el tiempo de espera a 120 segundos

      - name: Transferir el archivo comprimido a la VM
        run: |
          for i in {1..5}; do
            gcloud compute scp build.tar.gz rmanzimerica@$INSTANCE_NAME:/home/rmanzimerica --zone=$ZONE && break
            echo "Retrying scp in 15 seconds..."
            sleep 15
          done
          
      - name: Verificar archivos en la VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            ls -lt /home/rmanzimerica/asociacion_apetech
          " -- -o StrictHostKeyChecking=no


      - name: Descomprimir y mover el build en la VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            cd /home/rmanzimerica/asociacion_apetech
            rm -rf asociacion_apetech/build
            mkdir -p asociacion_apetech
            tar -xzf build.tar.gz -C /home/rmanzimerica/asociacion_apetech
            ls -lt /home/rmanzimerica/asociacion_apetech/build  # Verificar que los archivos estén ahí
          " -- -o StrictHostKeyChecking=no

      - name: Reiniciar servidor (si usas Nginx)
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo systemctl restart nginx  # Solo si usas Nginx
          " -- -o StrictHostKeyChecking=no
          
      - name: Verificar el estado de Nginx
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo systemctl status nginx
          " -- -o StrictHostKeyChecking=no
          
      - name: Revisar los logs de Nginx
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo tail -n 100 /var/log/nginx/error.log  # Revisa los últimos 100 registros de error
          " -- -o StrictHostKeyChecking=no
<<<<<<< HEAD

=======
>>>>>>> 621df50a43e6fe252d2af1300dabbdf5e698f59d







