name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Esto ejecutará el despliegue solo en el branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Deploy to VM
        env:
          INSTANCE_NAME: "apetech-vm"
          ZONE: "us-central1-a"  # Ajusta a la zona de tu VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            cd /home/rmanzimerica || exit 1
            if [ ! -d 'asociacion_apetech/.git' ]; then
              git clone https://github.com/rmanzi13/asociacion_apetech.git
            else
              cd asociacion_apetech
              git pull origin main
            fi
            cd asociacion_apetech &&
            npm install &&
            npm run build &&
            pm2 restart all
          "

