name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Esto ejecutará el despliegue solo en el branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  # Define las variables globalmente para el job
      INSTANCE_NAME: "apetech-vm"
      ZONE: "us-central1-a"  # Ajusta a la zona de tu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      - name: Comprimir la carpeta de construcción para la transferencia
        run: |
          tar -czf build.tar.gz build

      - name: Esperar propagación de clave SSH
        run: sleep 120  # Aumenta el tiempo de espera a 60 segundos

      - name: Transferir el archivo comprimido a la VM
        run: |
          for i in {1..5}; do
            gcloud compute scp build.tar.gz rmanzimerica@$INSTANCE_NAME:/home/rmanzimerica --zone=$ZONE && break
            echo "Retrying scp in 15 seconds..."
            sleep 15
          done

      - name: Descomprimir y mover el build en la VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            cd /home/rmanzimerica
            rm -rf asociacion_apetech/build
            mkdir -p asociacion_apetech
            tar -xzf build.tar.gz -C asociacion_apetech
            pm2 restart my-app || pm2 start /home/rmanzimerica/asociacion_apetech/Backend/app.js --name 'my-app'
          " -- -o StrictHostKeyChecking=no






