name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Esto ejecutará el despliegue solo en el branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  # Define las variables globalmente para el job
      INSTANCE_NAME: "apetech-vm"
      ZONE: "us-central1-a"  # Ajusta a la zona de tu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      - name: Comprimir la carpeta de construcción para la transferencia
        run: |
          tar -czf build.tar.gz build
          ls -lh build.tar.gz  # Verificar el tamaño del archivo

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Esperar propagación de clave SSH
        run: sleep 120  # Aumenta el tiempo de espera a 120 segundos

      - name: Transferir y desplegar build en la VM
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            mkdir -p /home/rmanzimerica/asociacion_apetech/build
            rm -f /home/rmanzimerica/asociacion_apetech/build.tar.gz
            tar -xzf build.tar.gz -C /home/rmanzimerica/asociacion_apetech/build
            echo 'Despliegue completado. Archivos en:'
            ls -lt /home/rmanzimerica/asociacion_apetech/build
          " -- -o StrictHostKeyChecking=no

      - name: Reiniciar servidor (si usas Nginx)
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo systemctl restart nginx  # Solo si usas Nginx
          " -- -o StrictHostKeyChecking=no
          
      - name: Verificar el estado de Nginx
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo systemctl status nginx
          " -- -o StrictHostKeyChecking=no
          
      - name: Revisar los logs de Nginx
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            sudo tail -n 100 /var/log/nginx/error.log  # Revisa los últimos 100 registros de error
          " -- -o StrictHostKeyChecking=no










