name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Esto ejecutará el despliegue solo en el branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY0 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "asociacion-apetech"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build  # Esto compila el proyecto en GitHub Actions

      - name: Copy build to VM
        env:
          INSTANCE_NAME: "apetech-vm"
          ZONE: "us-central1-a"
        run: |
          # Comprimir la carpeta de construcción para la transferencia
          tar -czf build.tar.gz build
          # Transferir el archivo comprimido a la VM
          gcloud compute scp build.tar.gz $INSTANCE_NAME:/home/rmanzimerica --zone=$ZONE
          # Descomprimir y mover el build en la VM
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command "
            cd /home/rmanzimerica
            if [ -d 'asociacion_apetech/build' ]; then
              rm -rf asociacion_apetech/build
            fi
            mkdir -p asociacion_apetech
            tar -xzf build.tar.gz -C asociacion_apetech
            pm2 restart all
          "



